name: CI
on: push
env:
  APP_NAME: my-app
jobs:
  build:
    runs-on: ubuntu-latest
    env:
      NODE_ENV: production
    steps:
    - uses: actions/checkout@v4
    - run: 'echo "Repo:   ${{ github.repository }}"'
    - run: 'echo "Actor:  ${{ github.actor }}"'
    - run: 'echo "Branch: ${{ github.ref_name }}"'
    - run: 'echo "SHA:    ${{ github.sha }}"'



